server:
  port: 8082
vault:
  uri: http://127.0.0.1:8200
  authentication: APPROLE
  app-role:
    role-id: 5669e456-c0d8-9a49-8631-67b0df91741d
    secret-id: 1db6426a-5ece-f2be-1665-92f72672f420
management.endpoints.web.exposure.include: "health,jolokia,metrics"
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  datasource:
    username: dev
    password: pass
    url: jdbc:mysql://localhost:3306/default?verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
